name: PR Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - uses: coursier/cache-action@v6.4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: sbt test
