name: PR Tests
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: "ubuntu-latest"
    services:
      docker:
        image: docker:dind
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
      - uses: coursier/cache-action@v6.4
      - uses: VirtusLab/scala-cli-setup@v1.5
      - run: scala-cli test branch
